apiVersion: v2
name: nextcloud-stack
description: Full Nextcloud stack (Nextcloud + MariaDB + Redis)
type: application
version: 1.1.0

dependencies:
  - name: nextcloud
    version: 9.2.0
    repository: https://nextcloud.github.io/helm/

  - name: mariadb
    version: 25.1.2
    repository: https://charts.bitnami.com/bitnami

  - name: redis
    version: 19.0.0
    repository: https://charts.bitnami.com/bitnami
