apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-nginx
  namespace: argo-cd
spec:
  project: default

  source:
    repoURL: https://github.com/Gabriel2k/Gitops-lab.git
    targetRevision: main
    path: apps/hello-nginx

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
