---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-credentials
  namespace: nextcloud
spec:
  encryptedData:
    mariadb-password: AgAT0eY3zHgvnQmFjz4X6Av+EjwRjQnu15J53AeE6R2qezRosREIy93EA1pIMzXBi+9ax/Enq0lNZV+j6eY/ZsIB7TNO7T19GlG3hj8GtBAe9jlkr/qlxB0vBJR+Jf6clzsUg+g+Tn/TbT+w/qsp0vv5il4oBiwmJnzFY+tWR4qNPHF8B8THBXUsHard+b6qx4HZmCGxB2nGKYeeQLwq2Tqhi5wkRANJGdhiYL2XKuBzsRJwCso+tsLbL7T2zmJIJPKgQE+VifTyyQkJsN5EpqSD0opH9K3C3NPa/QC7MNnYSDccFWB92ch0AZWXYno+GwbP2zeJTfAbOwcdO0/e9S3E3nNiJdzMUDBacVA0uWTKe984yxF0jnKlKf/x/w8pzsa4tbu9LdqEshCFw2ajuJBMoF6bflcMeObxLR0CWQxm4xKxjDTL3ruefIcf8XMORifMh8TbsopBV4848avGyiOty/Uvo0267yQUZBQom95Hq5aH0hYKnYE4ZB7qRXWPcmSHj8TutSf8pi3XLwWH5t7ylt6OXTImr2ubBZa53DdLEPOZxnXaN7NOKooPhEewy6B16uyq2a8zwXpXWVRlRfWZESCHBoCWoUwZoKoIIdT0sFPzqFeX0MaHxSmsixh1XS34wlDb9DguMnx+cMAFXg0OW9RoMduErQBb8uiM+PYA9xd/X8FsAhtvlRZHXNqxk51qM4P5T7n7yxlFIxAc2A==
    mariadb-root-password: AgCcSv+unwCzMB05t3Wu4DvaAiLMdXvo5J+4zoK2WjswXV2sPwgNtb9X5LeDIRcDLDs1hxJpyvQ+aDvimX21UDCvqXkftb3n1infVbhcNBM/zjuP/4HHLG0nZ0yaFnpUtQWss9CgINrIDVGxkEEAFvsGjVgASK2N5VACLNriggcW6xI3w3Tli3mHZ87Ce9gUCYIUUnJeA6oG/nW04XIenRfPtJMJAJgzUTB9DDtGcei+9yvaxJhyw/C7Tmwze7RBlctWuYpPA0t4mlNpdlQX8BFHFmIucaqxQmfTWpTTOff/e7PKsoe8/s7Dfm82KLUgi9qim87LtelJbmjhhzAPU1/FsFnyBzlIN7dfFg+wXw+Ug1X+bubOzdytzg+cKUM6hyOFdw7gu8hCi4qebr88s/R7k2/2ewbYSJYxA0GrAHT8oxVSK1ZAzwpZgJ9irCqrImm7e5ZnO8WCPOoaruRD/HSkSOhZ+wdDvknOB5vrlGrwMhCQDi8tXr1YByM74kpyAUGxDNcO6P4r+M0ZbwiVCA6pTLnaNENd8YjiZPTdS7/PPAWgqvE8yvz3Dn/gYEKWDTBXNF5uDZUFnf8TA1I+iNKMHeqs8L+TeXJKVDtsJ3Naif+3n8FQhwz8Lz+AFRwnxqyyzHdOzn95OpVqP1yo/tDoZ75tPute2Rxz2rs45QiDzI7mXuWPUhI5gnJfJ3PxuP8gVcnXr+MEop8bk3v9uM2DH0c=
  template:
    metadata:
      name: mariadb-credentials
      namespace: nextcloud
    type: Opaque
