---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-credentials
  namespace: nextcloud
spec:
  encryptedData:
    mariadb-password: AgAF4clUHQNHv+e8o2iJas+bZOZ8HWZMR4TxIb1siUzRKPb+HIurHm6YdgtuDaV6DJ7CrKHheW8NwQ3/7MqQFnuSfs81jdjuN3P0txPxDeGxndnD6Q9PoybCVhe3puaDnfhUEC5JOF6tIhwdcmtYV74IUU4OP5ENuHSl3WvDNoHZWDxHZwzcjnUFYmoyEj9bla7vXvvT8G4Ckb9gzaqiq9FD6j9U3T6iglaos5ceDkobFtsBFNZanMqhhC7z3Q1uu80YYL6CN3m3iFBOZtppANTsfqiN5Hmfo1bHc23f4UjDKmeO9NNK7O2RY48d2s+pUNAS5pOndV4ghIA67afsn/EztDlc0fGJp+6a7E1aXTq23RGWo8mz+VDE+TEE+ZnMX0yedxHZDChkeGkhpxFJ36r5NoOjqUt/Jemg34HBcyS8sfKOWd3fFp7iC4cWafNUbN0rFaCmY76GCdc/z+JMriAxjVkjkbWPUxayT7Iae3D3RpY3XZ6gUGoTyl6CK7hMxMe8p/b14rBvy5udC27l29dqyf/q0vCz7vcIczEsZZfIEeFTFAg+xJWwK9BQWoVnP9BcQv0r6gXzkI2S9E0IUTvVDEHqUX3GFOjuDbqZQ7W+rSo/TZnKHtyEl/KhLr3RuB5Qlr8rnC/xe/E/j+YdwmaxqXz2pihWzevH+JaAL6awsh4Ji32e9Y1gDbnaSFsGcdNhYnMpd1uOqVkVR41jqQ==
  template:
    metadata:
      name: mariadb-credentials
      namespace: nextcloud
    type: Opaque
