---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-credentials
  namespace: nextcloud
spec:
  encryptedData:
    nextcloud-password: AgCZUuoSuld7KWqnkRS/nRY5JUnlSOBazaqroiC+p51FC+t1BkVjUF0vWUhi3Rl4ifCx/u7qFTLTUu1AHY744Nqn5htfGHtg9C1jedIoyM58dwaMCM8sctGDMQ9pgDnSR+t2d1A0qOYsKVqHB2z64HE/sLUx8iGYZuR3BFCWWwrW52y6Zcch2RGdAtrDzB3IL2GIcAPTwBIIl1/NzVRYZN4uhuZghESDnJC1tOVrXtrcDrIxeKb/ZxmgjvVtx4YiIEtfDMwMwta9QdhMvgBS9keRyvl/sUNgVPNkZ/FAG55TlyTRBaD8PmjL2STvWRa01+oJPRWuPliwNqsaaHf6B64r46z0zqqSWF1RtpfPiAKdIwfz2IPpCYgq3CoJld4Xtl1ghwya679jOsl00+Wd91VUKp3j4Sh4TRwiTjjqn920He3fPykEjh9bq32RAxbit8w+6EXD5EttWgqNnjgxJVIwzpfEudN/xOWzs6l8zlco9yCnvfUETMPBOEs8vleD++aSHDvLM8Do6DkdefnrmbcC23RbVOYo4qtOyaHfiq3T9Jy9kXtxfCU0SDxgnbAEBiq1GsvJKLG6fBwyi213T4U+QYZmVhGqCL4jZtPaYFVXOy+5kVNqUmDB19EK+0Jz2pf4mijyiBjjvK0DVnKCKEsVjU2b00GKxK0V2fMPQ6yA15rhOqhNpolbKPeWEM3vh/LLpQfaWj+koSV5WxYKXQ==
    nextcloud-username: AgAbz4HNK+Q72ijhm+JvF3aP+iZ0WLWh0bgacTPGlAs9vl7s6gD9UrpdtNVsOHPjWEf2M9+6r8P6FbqKeIqo92x6CFjSOIs3XrlvDzKVwVKlQXRW9WvQNvF6RA1Uhs/E/6PHJeDrwg82eA2fzuhkESIJRBKxrHZUE8B4Coejil2AZ7WJFIXx/tib4/s8Ar1ZcxhQs8xxfNHaUD/9hnXsSgn7WUCteYkAY8tcWNVeHqWGxWoE+URKv8KLc4i6tnCXiQRiYSeX+v2V6Jq0MckhTvSA9tJFyxTYNauUrAvvvIh9wqwiEf9pWfVGfUVjQOasSEzvVt/8c23JN5pM+30NKnA6Xd14W6RO8hDL8iGyg91Jg0NtR3Qxp6cDROQOXobXPoqH4Mj3YLoJzoxY2UVZs88iXFGVRuc7PafI7Q1oBjZpqhQWWGdHGwqEQYZvXXsOq18a1zs2FeKueBumhdRCU7ZvnQMnkCxhuVgbd8oXBzM4vOJsEAPKmjEtPersBjJC64ztlv7pug4HStFI+dr/A7caQDMSr+E0C0C6VulLEtK6/7BGvwqU/M1IIHSvNFjwKuOItFcSGZf1dYZe2UChe04ldamdFfAI1OUNfGMXcPtTV4LKQwHJJs323p6CtyQtKhLy3VvAExmDuTOxlcgnRs027RppgnBobhhabgJoGdMiOgGgI4HAZnnpHwdlrETi6g4B5+aU1dj6
  template:
    metadata:
      name: nextcloud-credentials
      namespace: nextcloud
    type: Opaque
