---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: nextcloud
spec:
  encryptedData:
    redis-password: AgAnznCEJX0Zx1ShMYLgudzLCEOvcfrBOMR38Np+xpN6Ofvo1PjvtCWrh2yuoovbQLsLx7jxSK5omYl0scCUzC99iIVywUceX63ho03g94H3etVbwmUllvIwJ7R6ZDXxvpFTyaAtxU4rGbYiifxWrrGuiMXpyTQ708639v5jXZj+OhJSbe5HzkjiqgeSHgpZDzQZrCO1OsSSX8pNGijXUavw0XIW2dMSnC4NStCp4d8rI4bl6PABkm7er/hvAZc+3/B4tZ4cjUMk4U3/RoxtZDYI0wsE88TyY5qpN1T3BZlyVJUMB7H3qEWHSM3AVjuZ/3WZww9JUsydHxS/+lqoSdgJnsWdeDDBhCLFlCy5eyqjOidZjmabkQMDrRDx0RdWaWjlimjNlRhUx+pBjOcMVmg8PCRw6cDOF5Sk0Q1rr0DFzbRGB85mZVeA0mbOWDk4ZS72ngJScxa8TFr/KxepcUyGK5FIiT5n89BNnAFqWtBG/tH4gO4QmM4gwzmzbP2+JFi+uxbNuI2BH7k3Mh9TIbbPd4CE9Snu2og1WjwlZ84omH88JTL5T5kRjL8Aw7PUFaW99C07xueaGNwig7nHTMuIYdKYJlXK+ADSz0uXLJPdLjFu3036Px0/cGLvKok6a+sNCwTZNal1xFGjXlHRC3rn8Ny82LSLziskeifJv+8UJ0IxssU1p0VevU2t0eWnYuM2/iqLTUF3p5K1xXdY
  template:
    metadata:
      name: redis-credentials
      namespace: nextcloud
    type: Opaque
