---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgC44TxyBlZZh4IJUH4IF3QuXsctBqJpIz8/ONddHM79bR5RsZJWJCTqE++Uv8GMnRHFVTvbLKC/ij8HuZ/QjLHWU2NHGII5YRLHyGle5JxaI4svO++DeiNqCweRRfuyJfdPPSsV4IxauV4VlymGrWzXHsksF9ShSl9SFtcmbffiiyb+XlqdHrhFulcmJnWe9DAnmGbCdIjjxOqDgcJz2eq4M8B+FYL23MzB9ABVZMspIWOIoQIiLQplV7MrORSTxab5NYQUuqeIbEqxGEH766HpA7ZeNPfC4URvM3dOZ/a2nwhBqEqPcVAsYP/Cts74/xJADo/VOBsevcjkDvnycoWqpHHCM6QYKAOKtdRK2iUUrkKyTdbAHfF3dPcuzS4mLAP19po5DkMGWbl67iaaDNK3kZonBvMLFGBOkDFeyvil2vCroqkJGZOkqcDXV3RQz3sJSn7v3rd5wlG0rcriRgiMPwndERhIFGF7CPYU7eFuFYW4WbrS3GixZDqnhTsDJYu4jFAyDjao4+Nkt5qtJkz+zoFpD33w29mLIIkwwKjzmo6qO30vtCKsGHpIYE1NNSqyDPKT2Dr0IBeeA/h9uF76ARCkvcBecGU9Ji1Rz9+rLvWyfIYRL2sHw8396HjsfF3mkbM6whmAnr/6pYFvCm4FLRlW/BuUFxdbufWJC82nNIgVKaVXdziDigw3bVR/B52If3vYrG+SsPiCWEOChBS+QSoYg85JlN8fg37BW2OR8yOfHRyQKeNeZ82EJCQqOn9n/FvJ7Q==
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
